module.exports = {

  // ENTREPRISE
  ENTREPRISE_CREATED: "ENTREPRISE_CREATED",
  ENTREPRISE_UPDATED: "ENTREPRISE_UPDATED",
  ENTREPRISE_DELETED: "ENTREPRISE_DELETED",

  // UTILISATEUR
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_DELETED: "USER_DELETED",
  ROLE_CHANGED: "ROLE_CHANGED",

  // CONGES
  CONGE_CREATED: "CONGE_CREATED",
  CONGE_UPDATED: "CONGE_UPDATED",
  CONGE_DELETED: "CONGE_DELETED",
  CONGE_APPROVED: "CONGE_APPROVED",
  CONGE_REJECTED: "CONGE_REJECTED",
  CONGE_RESERVE_ACTIVATED: "CONGE_RESERVE_ACTIVATED",
  CONGE_RESERVE_SKIPPED: "CONGE_RESERVE_SKIPPED",

  // JOURS FERIES
  FERIE_CREATED: "FERIE_CREATED",
  FERIE_UPDATED: "FERIE_UPDATED",
  FERIE_DELETED: "FERIE_DELETED",

  // AUTHENTIFICATION
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  LOGOUT: "LOGOUT",

  // SECURITE
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_RESET_REQUEST: "PASSWORD_RESET_REQUEST",
  PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",
  TWO_FACTOR_ENABLED: "TWO_FACTOR_ENABLED",
  TWO_FACTOR_DISABLED: "TWO_FACTOR_DISABLED",
  TWO_FACTOR_VERIFIED: "TWO_FACTOR_VERIFIED",

  // COMPTEURS CONGES
  COUNTER_UPDATED: "COUNTER_UPDATED",
  COUNTER_DELETED: "COUNTER_DELETED",

  // IMPORTS CSV
  IMPORT_USERS_SUCCESS: "IMPORT_USERS_SUCCESS",
  IMPORT_USERS_FAILED:  "IMPORT_USERS_FAILED",
  IMPORT_CONGES_SUCCESS: "IMPORT_CONGES_SUCCESS",
  IMPORT_CONGES_FAILED:  "IMPORT_CONGES_FAILED",

  // INVITATIONS
  INVITE_EXPIRED: "INVITE_EXPIRED",

  // BLOCAGES METIER
  CONGE_OVERLAP_BLOCKED:  "CONGE_OVERLAP_BLOCKED",
  QUOTA_INSUFFICIENT:     "QUOTA_INSUFFICIENT",

  // EXPORTS
  EXPORT_CSV_GENERATED: "EXPORT_CSV_GENERATED",

  // PARAMETRES SYSTEME
  SYSTEM_SETTINGS_UPDATED: "SYSTEM_SETTINGS_UPDATED",
  SYSTEM_BACKUP_CREATED: "SYSTEM_BACKUP_CREATED",
  SYSTEM_BACKUP_DOWNLOADED: "SYSTEM_BACKUP_DOWNLOADED",
  SYSTEM_MAINTENANCE_TOGGLED: "SYSTEM_MAINTENANCE_TOGGLED",
  SYSTEM_RESTART_REQUESTED: "SYSTEM_RESTART_REQUESTED",
  SYSTEM_TEST_EMAIL_SENT: "SYSTEM_TEST_EMAIL_SENT"

};