module.exports = {

  // ENTREPRISE
  ENTREPRISE_CREATED: "ENTREPRISE_CREATED",
  ENTREPRISE_UPDATED: "ENTREPRISE_UPDATED",
  ENTREPRISE_DELETED: "ENTREPRISE_DELETED",

  // UTILISATEUR
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_DELETED: "USER_DELETED",
  ROLE_CHANGED: "ROLE_CHANGED",

  // CONGES
  CONGE_CREATED: "CONGE_CREATED",
  CONGE_UPDATED: "CONGE_UPDATED",
  CONGE_DELETED: "CONGE_DELETED",
  CONGE_APPROVED: "CONGE_APPROVED",
  CONGE_REJECTED: "CONGE_REJECTED",

  // JOURS FERIES
  FERIE_CREATED: "FERIE_CREATED",
  FERIE_UPDATED: "FERIE_UPDATED",
  FERIE_DELETED: "FERIE_DELETED",

  // AUTHENTIFICATION
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",

  // SECURITE
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_RESET_REQUEST: "PASSWORD_RESET_REQUEST",
  PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS"

};